tw-in-js/twind

- docs/css-in-js.md
- docs/grouping.md
- docs/plugins.md
- docs/tw.md
CSS-in-JS string values need to be quoted to produce valid CSS.
Resolves #21.
> Fix pseudo-element examples

- README.md
- docs/README.md
- docs/installation.md
- docs/observe.md
- package.json
- src/observe/index.ts
- src/shim/index.ts
This PR allows to use several shim instance (observer) on a page. This may be useful for advanced use cases like web components (#15).
See https://github.com/tw-in-js/twind/blob/twind-observe/docs/observe.md for details.
The basic idea is the following:
```js
import { observe } from 'twind/observe'
observe(document.body)
document.body.innerHTML = `
<main class="h-screen bg-purple-400 flex items-center justify-center">
<h1 class="font-bold text(center 5xl white sm:gray-800 md:pink-700)">
This is Twind!
</h1>
</main>
`
```
> feat: extract shim implementation into an own module for re-use

- docs/grouping.md
This PR includes a "Thinking in Groups" section of the grouping documentation, which uses a button example to demonstrate different approaches to grouping. It also includes verbiage to address the concern mentioned in https://github.com/tw-in-js/twind/discussions/59.
> docs: added "Thinking in Groups" section to grouping docs

- docs/installation.md
- docs/ssr.md
- package.json
- src/server/index.ts
- src/shim/server/index.ts
- src/shim/server/shim.test.ts
> feat: move shim server side into an own module

- .github/workflows/ci.yml
- docs/plugins.md
- package.json
- src/__tests__/api.json
- src/__tests__/api.test.ts
- src/__tests__/hash.test.ts
- src/__tests__/plugins.test.ts
- src/twind/configure.ts
- src/twind/plugins.ts
Some tailwind classes use global styles to reset their css properties
on every element so they do not leak to child elements.
Fixes #84
> feat: allow plugins to create global styles

- README.md
Looks like a link directly to the channel doesn't work (at least it doesn't for me)
> Update Discord link to invitation

- README.md
- docs/README.md
- docs/components.md
- docs/css-in-js.md
- docs/plugins.md
- docs/setup.md
- example/test.js
- src/__tests__/api.test.ts
- src/__tests__/apply.test.ts
- src/__tests__/dark-mode.test.ts
- src/css/css.test.ts
- src/css/index.ts
- src/twind/apply.ts
- src/twind/configure.ts
- src/twind/instance.ts
- src/twind/presedence.ts
- src/twind/serialize.ts
- src/twind/translate.ts
- src/types/css.ts
- src/types/theme.ts
- src/types/twind.ts
See this https://github.com/tw-in-js/twind/pull/83#issuecomment-760387694 to try it out.
Resolve #73
> feat: tw.apply for component like styles

- docs/components.md
- docs/css-in-js.md
- src/__tests__/apply.test.ts
- src/css/README.md
- src/css/css.test.ts
- src/css/index.ts
- src/twind/apply.ts
- src/twind/directive.ts
- src/twind/plugins.ts
Currently `apply`, `css`, `keyframes` and `animation` support non-tw usage:
```js
document.body.className = apply`bg-gray-50 text-gray-800`
const bounce = keyframes`...`
document.body.style.animation = `${bounce} 1s ease infinite`
```
This works as the returned function have `toString` and `valueOf` method which use the bound `tw` to generate the styles. Using a custom `tw` instance is supported by:
```js
const { tw } = create(/* options */)
const kf = keyframes.bind(tw)
// Or providing tw on invocation
const bounce = keyframes.call(tw, {
/* same as above */
})
```
This feature is quite difficult to understand for beginners and maybe confusing when stumbled on it in the docs. By removing it we can enforce that only explicit `tw` calls generate and inject styles. **No magic**!
I would like …
> refactor: remove support for non-tw usage

- docs/css-in-js.md
- src/css/README.md
- src/css/css.test.ts
- src/css/index.ts
The `screen` directive allows you to create media queries that reference your breakpoints by name instead of duplicating their values in your own CSS.
For example, say you have a `sm` breakpoint at `640px` and you need to write some custom CSS that references this breakpoint.
Instead of writing a raw media query that duplicates that value like this:
```js
css`
@media (min-width: 640px) {
/* ... */
}
`
```
...you can use the `screen` directive and reference the breakpoint by name:
```js
import { css, screen, apply } from 'twind/css'
// With template literal
css`
${screen('sm')} {
/* ... */
}
${screen('md', css` /* ... */ `)}
${screen('lg', css({ /* ... */ }))}
${screen('xl', { /* ... */ })}
${screen('2xl', apply` ... `)}
`
// With object notation
css(
screen('md', css` /* ... */ `), …
```
> feat: screen directive

- src/__tests__/api.json
- src/__tests__/api.test.ts
- src/__tests__/apply.test.ts
- src/__tests__/dark-mode.test.ts
- src/__tests__/dom.test.ts
- src/__tests__/hash.test.ts
- src/__tests__/plugins.test.ts
- src/css/css.test.ts
- src/css/index.ts
- src/internal/util.ts
- src/sheets/dom.test.ts
- src/shim/server/shim.test.ts
- src/twind/decorate.ts
- src/twind/plugins.ts
- src/twind/presedence.ts
- src/twind/theme.ts
- src/types/theme.ts
- src/types/util.ts
Support more Tailwind [breakpoints](https://tailwindcss.com/docs/breakpoints) in theme screens
```js
setup({
theme: {
extend: {
screens: {
standalone: { raw: '(display-mode:standalone)' },
portrait: { raw: '(orientation: portrait)' },
print: { raw: 'print' },
special: [
// Sidebar appears at 768px, so revert to `sm:` styles between 768px
// and 868px, after which the main content area is wide enough again to
// apply the `md:` styles.
{ min: '668px', max: '767px' },
{ min: '868px' },
],
},
},
},
})
tw`standalone:text-black`
tw`portraitt:text-black`
tw`print:text-black`
tw`special:text-black`
```
Fixes #20
/cc @tw-in-js/contributors
> feat: arrays and objects with raw, min or max properties for screen

- src/__tests__/api.test.ts
- src/twind/instance.ts
- src/types/twind.ts
This PR adds a `tw.theme` function to lookup theme values.
Later we can expose other context properties as well (like `css` for #96)
> fix: allow to access the theme via tw.theme

- docs/getting-started/css-in-js.md
- docs/getting-started/styling-with-twind.md
- src/__tests__/api.test.ts
- src/css/css.test.ts
- src/css/index.ts
- src/twind/configure.ts
- src/twind/serialize.ts
- src/twind/translate.ts
- src/types/twind.ts
This PR adds `@screen` and `@apply` at-rules which work like their function counterparts [screen](https://twind.dev/docs/handbook/getting-started/css-in-js.html#screen-directive) and [apply](https://twind.dev/docs/handbook/getting-started/styling-with-twind.html#the-apply-function):
**@apply**
```js
// Object Notation
tw(() => ({
'@apply': 'font-bold py-2 px-4 underline',
// '@apply': ['font-bold py-2 px-4', false && underline'],
color: 'fuchsia',
transform: 'translateY(-1px)',
})
// with twind/css
css`
@apply font-bold underline;
color: fuchsia;
@apply py-2 px-4;
transform: translateY(-1px);
`
css`
@apply ${['font-bold', false && 'underline', 'py-2 px-4']};
color: fuchsia;
`
```
=>
```css
.tw-1dlm15h {
font-weight: 700;
padding-bottom: 0.5rem;
padding-top: 0.5rem;
padding-left: 1rem; …
```
> @screen and @apply

- src/__tests__/api.test.ts
- src/__tests__/apply.test.ts
- src/__tests__/preflight.test.ts
- src/css/css.test.ts
- src/internal/util.ts
- src/twind/serialize.ts
- src/types/css.ts
- src/types/twind.ts
Add support for several `@font-face` rules:
```js
import { setup } from 'twind'
setup({
theme: {
extend: {
fontFamily: {
'proxima-nova': '"Proxima Nova"',
},
},
},
preflight: {
'@font-face': [
{
fontFamily: 'Proxima Nova',
fontWeight: '400',
src: 'url(/fonts/proxima-nova/400-regular.woff) format("woff")',
},
{
fontFamily: 'Proxima Nova',
fontWeight: '500',
src: 'url(/fonts/proxima-nova/500-medium.woff) format("woff")',
},
]
}
})
```
or using `css`:
```js
import { setup } from 'twind'
import { css } from 'twind/css'
setup({
preflight: (preflight) =>
css`
${preflight}
@font-face {
font-family: Proxima Nova;
font-weight: 400;
src: url(/fonts/proxima-nova/400-regular.woff) format("woff");
}
@font-face {
font-family: Proxima Nova;
font-weight: 500;
src: url(/fonts/proxima-nova/500-medium.woff) …
```
> fix: support several @font-face rules

- src/__tests__/api.json
- src/__tests__/api.test.ts
- src/twind/decorate.ts
- src/twind/presedence.ts
This PR allows to negate [pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) variants using `not-`prefix which will be expanded to ` :not(...)`.
Examples:
| Class name                         | Selector                                                    |
| ---------------------------------- | ----------------------------------------------------------- |
| `not-focus:invalid:border-red-500` | `.not-focus\\:invalid\\:border-red-500:not(:focus):invalid` |
| `invalid:not-focus:border-red-500` | `.invalid\\:not-focus\\:border-red-500:invalid:not(:focus)` |
| `not-disabled:focus:font-bold`     | `.not-disabled\\:focus\\:font-bold:not(:disabled):focus`    |
| `not-last-child:mb-5`              | `.not-last-child\\:mb-5:not(:last-child)`                   |
Core and …
> fix: support `not-` prefix for pseudo classes

- package.json
- src/__tests__/api.json
- src/__tests__/api.test.ts
- src/internal/util.ts
- src/twind/configure.ts
- src/twind/parse.ts
- src/twind/plugins.ts
- src/twind/theme.ts
- src/twind/translate.ts
- yarn.lock
This PR adds the new tailwindcss square bracket notation like `top-[-113px]`. Works with variants too, like `md:top-[-113px]`.
This works in places where a theme value would be used. So almost everywhere.
I would like to add a config option to disable this feature. But I'm unsure of the name. Any pointers?
Which one do you prefer: arbitraryValues or dynamicValues?
---
Here are some examples: _Not everyone works right now – working on colors vs other value_
```
bg-[#0f0]
bg-[#ff0000]
bg-[#0000ffcc]
bg-[hsl(0,100%,50%)]
bg-[hsla(0,100%,50%,0.3)]
bg-[rgb(123,123,123)]
bg-[rgba(123,123,123,var(--tw-bg-opacity))]
bg-opacity-[0.11]
border-[#f00]
border-[2.5px]
duration-[2s]
grid-cols-[200px,repeat(auto-fill,minmax(15%,100px)),300px]
grid-cols-[minmax(100px,max-content)repeat(auto-fill,200px)20%] …
```
> feat: support arbitrary values using square bracket notation

- src/__tests__/api.json
- src/twind/configure.ts
- src/twind/decorate.ts
This PR allows using [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) as variants.
| Class Name | Selector |
|------------|-----------| 
| `[lang]:font-bold` | `[lang\]\:font-bold[lang`|
| `not-[lang]:italic`| `.not-\[lang\]\:italic:not([lang])` |
| `[aria-expanded='true']:font-bold` | `[aria-expanded\=\'true\'\]\:font-bold[aria-expanded='true']`|
| `[data-reach-menu-item][data-selected]:bg-red-300` | `[data-reach-menu-item\]\[data-selected\]\:bg-red-300[data-reach-menu-item][data-selected]`|
| `[href^='#']:bg-yellow-400` | `[href\^\=\'\#\'\]\:bg-yellow-400[href^='#']`|
| `[href*='example']:bg-gray-300` | `[href\*\=\'example\'\]\:bg-gray-300[href*='example']`|
| `[href$='.org']:bg-red-400` | `[href\$\=\'\.org\'\]\:bg-red-400[href$='.org']`|
| …
> feat: support attribute selector variants

- package.json
- src/__tests__/api.json
- src/__tests__/prefix.test.ts
- src/twind/configure.ts
- src/twind/parse.ts
- src/types/twind.ts
This PR adds support for the important modifier `!` as prefix to align the syntax with windicss and tailwindcss-jit:
| Rule | Class Names |
|------|-------------|
| `!text-center` | `!text-center` |
| `!-m-8` | `!-m-8` |
| `!(text-center font-bold)` | `!text-center !font-bold` |
| `hover:!(text-center font-bold)` | `hover:!text-center hover:!font-bold` |
| `!hover:(text-center focus:font-bold)` | `hover:!text-center hover:focus:!font-bold` |
| `text!(xl underline)` | `!text-xl !text-underline` |
| `!text(xl underline) md:!m(-8)` | `!text-xl !text-underline md:!-m-8` |
The suffix syntax is still supported but the emitted class is transformed to the new syntax: `font-bold!` -> `!font-bold`
/cc @tw-in-js/contributors
> support important modifier as prefix and for groups

- docs/migration-guides/tailwind.md
Fixes #193
I have updated the link to the what I believe is the intended URL (https://twind.dev/handbook/configuration.html), as that contains details on the mentioned features
> Update link in tailwind migration guide to point to configuration page

- docs/handbook/grouping-syntax.md
Fixes an inconsistency between the 'before variant grouping' and 'after variant grouping' examples.
> Docs: correct typo in variant grouping section

- docs/handbook/quick-reference.md
Minor copy/paste error, more than likely.
Edit: On a semi-related note, hitting the hashes next to any page title results in the URL fragment being `frontmatter-title` (e.g., `https://twind.dev/handbook/configuration.html#frontmatter-title`), which doesn't seem intentional.
> docs: Updating quick-reference link

- src/colors/index.ts
- src/index.ts
- src/twind/configure.ts
- src/twind/expand.ts
- src/twind/helpers.ts
- src/twind/parse.ts
Closes #195
Allows users to transform Twind's grouped syntax into the expanded form. This can be useful when paired with prerendering, as it allows you to remove the runtime requirement of Twind altogether (depending on your styles of course).
While writing this I thought of the name `expandGroups`, though not sure if that's better or worse than the suggested `ungroup`. Thought I'd bring it up here, but happy to edit to whatever your preference is.
> feat: Export group expansion utility

- src/twind/apply.ts
- src/twind/configure.ts
- src/twind/instance.ts
- src/twind/parse.ts
- src/types/twind.ts
This Pull Request does not change runtime logic, it just replaces `unknown[]` specifically when used for `apply()`, `process()`, `tw()`, and `parse()` (which now supports a `string` function argument recently introduced in PR #233 to expose "expand" APi)
Note that I also initially attempted to improve typings in the CSS Factory, but the ramifications were so deep and intricate that I found myself lost in `any`/`unknown` hell :) ... so I aborted and decided to propose this narrow-scope PR instead.
This PR passes `yarn build` and `yarn lint`, but note that in the `main` branch `yarn test` and `yarn test:coverage` fail with the following error (unrelated to this PR):
`twind/colors  "new colors are available"`
```
Expected values to be deeply equal:  (equal)
··[
Actual: …
```
> TypeScript typings improvement: replace `unknown[]` used in `apply()`, `process()`, `tw()`, and `parse()`

- src/__tests__/plugins.test.ts
- src/twind/translate.ts
This PR fixes #189 
The availability of the plugin is checked by the expressions `const plugin = plugins[id]` & `typeof plugin === 'function'`, but this causes error when the plugin candidate id is the name of Object's method (such as `toLocaleString`). This PR fixes that detection routine by using `hasOwnProperty` method.
> fix: fix plugin detection routine

- examples/with-sveltekit/src/routes/__layout.svelte
small fix for sveltekit example; see: https://svelte.dev/docs#component-format-script-context-module
> fix: sveltekit example __layout

- README.md
Was browsing the docs and saw the formatting was off. Can't escape backticks in GitHub markdown; it instead wants you to group multiple backticks to create pairs.
Note: there is in fact a zero width space in that backtick triplet, which is why this works and pairs where it does.
Corrects a minor typo as well.
> docs: Correct named shortcut formatting

- .changeset/honest-spoons-cross.md
- packages/twind/src/nested.ts
Native function methods like `apply`, `call` or `bind` should not result in creating named classes of these functions nor brick their functionality.
This of course prevents the user from using any of these native method names for naming their components but I don't think having the ability to name a component class `apply` should take priority over being able to use native JS methods.
Resolves https://github.com/tw-in-js/twind/issues/268
> fix: pass through native methods in "nested" proxy

- packages/twind/README.md
Very minor, but the docs for the main twind package reference `inject` which seems to have been replaced with `inline`.
Browsing through the history, the link doesn't look to have ever been functional, so maybe just there as a TODO? Regardless I updated it, but thought I'd mention that it doesn't link up to anything at the moment.
> docs: Update reference of `inject` to `inline`

- examples/with-remix/README.md
- examples/with-remix/remix.config.js
- fixed link to twind config
- added [`serverDependenciesToBundle`](https://remix.run/docs/en/v1/api/conventions#serverdependenciestobundle) in remix config
> improve remix example

- docs/handbook/getting-started.md
> docs: Correct tailwind documentation link in getting-started page

- docs/handbook/configuration.md
Hey,
I was using the documentation and realized that there was a simple typo in the example from google fonts. Fixed it.
> font import typo in documentation

- documentation/migration.md
The href for links after “There are lots of things possible.” had a typo in the href.
> Fix broken link in `migration.md`

- docs/handbook/extended-functionality.md
Noticed that Extended Functionality was showing twice in the left hand menu of the docs, tracked it down to having two 2-size headers with the same content. Looks like it just needed removed.
> Removed duplicate documentation sections in extended-functionality

- docs/usage-guides/svelte.md
minor fix for readability, the extra `"`s aren't needed
> fix typo in `svelte.md`

- .changeset/cuddly-rules-listen.md
- packages/twind/src/rules.ts
In line with tailwindcss hint syntax: https://tailwindcss.com/docs/adding-custom-styles#resolving-ambiguities
Given a color/fill/stroke section check if user provided a value type hint and if so respect it and remove it from further parsing.
Currently does not support the other commonly used `length` type hint from tailwind (but this one should with the current code always win over untyped or ambiguous values anyway so I think we can omit it.
> Given `text-[var(--brand)]` (interpreted as ambiguous) still resolves to `font-size: var(--brand)`. Using the color type hint `text-[color:var(--brand)]` now however returns `color: var(--brand)` in line with tailwind's syntax.
Resolves #299
> Respect color type hint when parsing arbitrary color values

- src/__tests__/api.json
- src/twind/plugins.ts
border colors with edge specifiers now work :)
> add border edge colors

- .changeset/nervous-pandas-itch.md
- packages/core/src/internal/warn.ts
You might find our contributing section about [Submitting Pull Requests](https://github.com/tw-in-js/twind/blob/main/CONTRIBUTING.md#submitting-pull-requests) helpful.
---
Add `cancelable: true` in warn.ts so the `event.defaultPrevented` can actually becomes `true` (see: #403).
> fix: "warn" message doesn't respect `event.preventDefault()` (fix #403)

- examples/with-remix_react-v18/remix.config.js
This was still referencing `@twind/with-remix` which is deprecated in favor of `@twind/with-react`
> fix: remix.config.js serverDependenciesToBundle
